Remove the gazebo-ci-pr_any-ubuntu-none jobs
ignition-tooling/release-tools pull request #300
Opened 2020-10-01 22:05 UTC by j-rivero

The PR removes the -none job that is part of the Gazebo CI in pull request. The results are covered by the use ci-pr_any-ubuntu-gpu-nvidia job.

2020-10-01 22:22 UTC, chapulina approved these changes

2020-10-01 22:24 UTC, scpeters requested changes
I think there's just a little bit more that should be removed: f28006be9ebe053c2d8ac7e3a5e2be722e256c17

I'd like to test this with a dsl job before merging

2020-10-02 14:50 UTC, j-rivero commented
> I'd like to test this with a dsl job before merging

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=_dsl_gazebo&build=709)](https://build.osrfoundation.org/view/All/job/_dsl_gazebo/709/)

```
Unreferenced items:
    GeneratedJob{name='gazebo-ci-master-bionic-amd64-gpu-none'}
    GeneratedJob{name='gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none'}
Disabled items:
    GeneratedJob{name='gazebo-ci-master-bionic-amd64-gpu-none'}
    GeneratedJob{name='gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none'}
Finished: SUCCESS
```

2020-10-02 18:00 UTC, scpeters approved these changes

2020-10-02 21:21 UTC, merged