Add CMake warnings to Windows/OsX jobs
ignition-tooling/release-tools pull request #510
Opened 2021-09-09 15:24 UTC by j-rivero

closes #509 

Tested locally, testing it in the buildfarm will enable the warnings for all Gazebo/Ignition jobs at once, don't want to have it uncontrolled for running CI at the moment.

I expect a good bunch of unstable builds after the merge.

2021-09-09 17:02 UTC, nuclearsandwich approved these changes

2021-09-09 17:46 UTC, scpeters approved these changes

2021-09-09 20:50 UTC, chapulina approved these changes

2021-10-06 14:51 UTC, j-rivero commented
> Before enabling this, as discussed offline, we would need a way to opt-in/opt-out the different libraries to avoid multiples warnings to be land at once.

Implemented in 0bd80fa, only enabled for ignition-cmake. In manual job test generation on my machine:
```
release-tools2/jenkins-scripts/dsl on  warns_osx_win [?] ❯ grep -i warnings.cmake *brew*
ignition_cmake-ci-ign-cmake2-homebrew-amd64.xml:                <io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-ign-cmake2-homebrew-amd64.xml:                </io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-main-homebrew-amd64.xml:                <io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-main-homebrew-amd64.xml:                </io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-pr_any-homebrew-amd64.xml:                <io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-pr_any-homebrew-amd64.xml:                </io.jenkins.plugins.analysis.warnings.Cmake>
release-tools2/jenkins-scripts/dsl on  warns_osx_win [?] ❯ grep -i warnings.cmake *-win*
ignition_cmake-ci-ign-cmake2-windows7-amd64.xml:                <io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-ign-cmake2-windows7-amd64.xml:                </io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-main-windows7-amd64.xml:                <io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-main-windows7-amd64.xml:                </io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-pr_any-windows7-amd64.xml:                <io.jenkins.plugins.analysis.warnings.Cmake>
ignition_cmake-ci-pr_any-windows7-amd64.xml:                </io.jenkins.plugins.analysis.warnings.Cmake>
```

2021-10-06 18:49 UTC, scpeters approved these changes

2021-10-06 19:18 UTC, scpeters requested changes
actually the windows build has cmake warnings:

[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_cmake-ci-ign-cmake2-windows7-amd64&build=94)](https://build.osrfoundation.org/job/ignition_cmake-ci-ign-cmake2-windows7-amd64/94/) https://build.osrfoundation.org/job/ignition_cmake-ci-ign-cmake2-windows7-amd64/94/

2021-10-07 21:43 UTC, merged