Improved version of source_changelog
ignition-tooling/release-tools pull request #541
Opened 2021-10-27 15:22 UTC by j-rivero

While reading the latest changes to github product cli I just noticed that they have an script to generate changelog entries: https://github.com/cli/cli/blob/4e219a9c8f4fb2b38c2b9ff001a39729b58d61f8/script/changelog.

In trunk (hello subversion) branch in the repository [they have changed it to call github API](https://github.com/cli/cli/commit/1464a8a0f35397ccdbf2c07aedddcbf35bd70c1d#diff-0509cbc694c8e2bf62967b89f73ac64b66f8c0cd1a263a1a009b10bc3c1ff313), which should probably be the way to go for us too.

Meanwhile I modified their script a little bit, I think is ready to test. A quick launch on ign-tools repository seems fine (note I disabled the check for external contributors, openrobotics emails are filtered out):
```
## Ignition Tools 1.x (2021-10-27)

1. Fix windows colcon build
    * [Pull request #65](https://github.com/ignitionrobotics/ign-tools/pull/65)
    * A contribution from: Steve Peters <scpeters@openrobotics.org>

1. Fix use of Backward on macOS and add a unit test 
    * [Pull request #67](https://github.com/ignitionrobotics/ign-tools/pull/67)
    * A contribution from: Addisu Z. Taddese <addisu@openrobotics.org>

1. Support colcon in windows CI
    * [Pull request #66](https://github.com/ignitionrobotics/ign-tools/pull/66)
    * A contribution from: Steve Peters <scpeters@openrobotics.org>

1. Add flag to get standard-compliant exception handling
    * [Pull request #68](https://github.com/ignitionrobotics/ign-tools/pull/68)
    * A contribution from: Addisu Z. Taddese <addisu@openrobotics.org>

```

Note: to review it, just look at the plain raw file, diff make not sense here.

2021-12-23 03:10 UTC, scpeters commented
I like the automatic tag detection, that's a definite improvement. I think it could use some more documentation about the git magic used to detect the tag, but I think it is a great idea.

One difference I noticed is how it treats merge-forward pull requests. I just tested it with `sdf10` as I prepare for a 10.7.0~pre1 prerelease, and it listed two merge-forward pull requests in the changelog but didn't list the commits that were merged forward. With this branch it shows 6 new Changelog entries, while the `master` branch version of this script generates 40 entries. I realize that there's been recent discussion about whether to show features repeatedly in different major versions of the changelog, and I can't remember what the result of that discussion was, but I think we should consider how we want this script to handle merge commits.

2021-12-23 03:29 UTC, scpeters commented
I started with this branch for https://github.com/ignitionrobotics/sdformat/pull/799 but finished by hand to include the forward-port PRs

2021-12-23 04:59 UTC, chapulina commented
Oh I totally forgot about this PR!

> it listed two merge-forward pull requests in the changelog but didn't list the commits that were merged forward. 

Ah yeah we should have all the commits that have been merged forward

2022-04-28 17:58 UTC, j-rivero commented
> Oh I totally forgot about this PR!
> 
> > it listed two merge-forward pull requests in the changelog but didn't list the commits that were merged forward.
> 
> Ah yeah we should have all the commits that have been merged forward

Found some time to make the changes. I tried to use the same git log approach that we currently have to reflect merges in the same way. [d577f2a](https://github.com/ignition-tooling/release-tools/pull/541/commits/d577f2a9089cf1b97f03b3fe1dfb985c35cf08bd).

2022-05-03 00:03 UTC, chapulina requested changes
Nice! I like it how it automatically picks up the tag.

There's still some issue with the merge commits though. If I run this on `ign-gazebo` right now, I only get the forward-port PR, but there are many other commits in the diff:

https://github.com/ignitionrobotics/ign-gazebo/compare/ignition-gazebo6_6.9.0...ign-gazebo6

2025-11-11 17:01 UTC, closed without merging